### ISSUE TITLE
Streaming Messages

### ISSUE THREAD

**Issue by kreneskyp** [kreneskyp/ix#131]
Tracking ticket for streaming responses from AI models.

- [x] Implement LangChain callbacks (#130)
- [x] define stream protocol (message objects and streams) #142 
- [x] django channels / graphql subscription (worker connection partially implemented in #130) #142
- [x] frontend updates  #142

**Comment by kreneskyp** [comment]
finished in #142
