### ISSUE TITLE
Convert Chat API to FastAPI

### ISSUE THREAD

**Issue by kreneskyp** [kreneskyp/ix#151]
The chains API and frontend need to be converted to Pydantic + FastAPI.

- [x] Pydantic Types & FastAPI endpoints: #153 
       - Create, update, delete chats  
       - send_input 
- [ ] UI updates
    - [x] conversion to FastAPI
         - [x] ChatInput (send inputs to agent) (in progress)
         - [x] ChatMessages (loading complete messages at page load) (in progress)
         - [x] chats can be deleted #157 
    - [ ] Chat view should not create chat until a message is sent. Currently created when loading view and generates lots of spam and empty chats.  https://github.com/kreneskyp/ix/issues/171

**Comment by kreneskyp** [comment]
Closing as only remaining work is cleanup that wasnt specific to fastAPI
